
package client;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import output.CustomOutputStream;

/**
 *
 * @author Manuel
 */
public class EchoClientGUI extends javax.swing.JFrame {

    private int threadCounter = 0;
    private Socket socket;

    public EchoClientGUI() {
        initComponents();
        jTA_output.setEditable(false);
       
    }

    public synchronized void sendAndReciveData() throws UnknownHostException, IOException, InterruptedException {
        PrintStream printStream = new PrintStream(new CustomOutputStream(jTA_output));
        // re-assigns standard output stream and error output stream
        System.setOut(printStream);
        System.setErr(printStream);
        System.out.println("connecting....");
        InetAddress addr = InetAddress.getLocalHost();
        socket = new Socket(addr, 9991);

        InputStream input = socket.getInputStream();
        BufferedReader reader = new BufferedReader(new InputStreamReader(input));

        System.out.println("Enter your Name:");
        ClientThread ct = new ClientThread(reader,jA_Room);
        Thread thread = new Thread(ct);
        thread.start();
    }

    public void sendToServer(String lineToSend) {
        OutputStream output;
        try {
            output = socket.getOutputStream();
            PrintWriter writer = new PrintWriter(output);
            writer.println(lineToSend);
            writer.flush();
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }

    public void closeConnection() throws IOException {
        System.exit(400);
        socket.close();
    }

    public class ClientGUIThread extends Thread {

        String name;
        EchoClientGUI client;

        public ClientGUIThread(String name, EchoClientGUI client) {
            this.client = client;
            this.name = name;
            start();
        }

        @Override
        public void run() {
            try {
                client.sendAndReciveData();
            } catch (IOException | InterruptedException ex) {
                System.out.println("Error: " + ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jT_Input = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_output = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jA_Room = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 316));

        jT_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                onSendTextEnter(evt);
            }
        });
        getContentPane().add(jT_Input, java.awt.BorderLayout.PAGE_END);

        jTA_output.setColumns(20);
        jTA_output.setRows(5);
        jScrollPane1.setViewportView(jTA_output);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jA_Room.setEditable(false);
        jA_Room.setColumns(20);
        jA_Room.setRows(5);
        jA_Room.setBorder(javax.swing.BorderFactory.createTitledBorder("Room:"));
        jScrollPane3.setViewportView(jA_Room);

        getContentPane().add(jScrollPane3, java.awt.BorderLayout.LINE_END);

        jMenu1.setText("Client");

        jMenuItem1.setText("Connect");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onStartConnection(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("DisConnect");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDisConnect(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Close");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClose(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onStartConnection(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onStartConnection
        threadCounter++;
        new ClientGUIThread("ClientGUIThread " + threadCounter, this);
    }//GEN-LAST:event_onStartConnection

    private void onDisConnect(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDisConnect
        try {
            closeConnection();
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_onDisConnect

    private void onClose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClose
        onDisConnect(evt);
    }//GEN-LAST:event_onClose

    private void onSendTextEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onSendTextEnter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            sendToServer(jT_Input.getText());
            jTA_output.append(jT_Input.getText() + "\n");
            jT_Input.setText("");
        }
    }//GEN-LAST:event_onSendTextEnter

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EchoClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EchoClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EchoClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EchoClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EchoClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jA_Room;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTA_output;
    private javax.swing.JTextField jT_Input;
    // End of variables declaration//GEN-END:variables
}
